# -*- coding: utf-8 -*-
"""DataLoad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1biPaUlHZmuIDUtU70jWYH7bo5qkECunJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
import joblib
from wordcloud import WordCloud

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Embedding, GlobalAveragePooling1D, Dropout

#@title Data Load
def load_data(train_path, test_path):
    print("\n--- [1] Loading Data ---")
    print(f"Train path: {train_path}")
    print(f"Test path : {test_path}")

    if not os.path.exists(train_path) or not os.path.exists(test_path):
        print(f"\n[ERROR] File tidak ditemukan!")
        print("Jika di Google Colab, pastikan Drive sudah di-mount.")
        print("Jika di Lokal, pastikan file ada di folder 'data/'.")
        sys.exit()

    try:
        df_train = pd.read_csv(train_path, sep='\t', on_bad_lines='skip')
        df_test = pd.read_csv(test_path, sep='\t', on_bad_lines='skip')
        print(f"Sukses memuat data. Train shape: {df_train.shape}, Test shape: {df_test.shape}")
        return df_train, df_test
    except Exception as e:
        print(f"[ERROR] Gagal membaca file: {e}")
        sys.exit()

def preprocess_data(df_train, df_test):
    print("\nPreprocessing Data")

    # Gabungkan kolom teks
    text_cols = ['benefitsReview', 'sideEffectsReview', 'commentsReview']
    for col in text_cols:
        df_train[col] = df_train[col].fillna('')
        df_test[col] = df_test[col].fillna('')

    df_train['text'] = df_train['benefitsReview'] + " " + df_train['sideEffectsReview'] + " " + df_train['commentsReview']
    df_test['text'] = df_test['benefitsReview'] + " " + df_test['sideEffectsReview'] + " " + df_test['commentsReview']

    # Encode target 'effectiveness'
    le = LabelEncoder()
    y_train = le.fit_transform(df_train['effectiveness'])
    try:
        y_test = le.transform(df_test['effectiveness'])
    except ValueError:
        print("Warning: Label baru ditemukan di test set. Refitting encoder...")
        le.fit(pd.concat([df_train['effectiveness'], df_test['effectiveness']]))
        y_train = le.transform(df_train['effectiveness'])
        y_test = le.transform(df_test['effectiveness'])

    print(f"Classes encoded: {list(le.classes_)}")
    return df_train['text'], y_train, df_test['text'], y_test, list(le.classes_), le