# -*- coding: utf-8 -*-
"""Execution Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1biPaUlHZmuIDUtU70jWYH7bo5qkECunJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
import joblib
from wordcloud import WordCloud

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Embedding, GlobalAveragePooling1D, Dropout

#@title Execution
if __name__ == "__main__":
    COLAB_TRAIN = '/content/drive/MyDrive/Data Science/drug+review+dataset+druglib+com/drugLibTrain_raw.tsv'
    COLAB_TEST = '/content/drive/MyDrive/Data Science/drug+review+dataset+druglib+com/drugLibTest_raw.tsv'

    if os.path.exists(COLAB_TRAIN):
        train_path, test_path = COLAB_TRAIN, COLAB_TEST
        base_dir = '/content/drive/MyDrive/Data Science/models/'
        if not os.path.exists(base_dir): os.makedirs(base_dir)
    else:
        base_dir = os.path.dirname(os.path.abspath(__file__))
        data_dir = os.path.join(base_dir, '..', 'data')
        train_path = os.path.join(data_dir, 'drugLibTrain_raw.tsv')
        test_path = os.path.join(data_dir, 'drugLibTest_raw.tsv')

        if not os.path.exists(train_path):
             train_path = 'drugLibTrain_raw.tsv'
             test_path = 'drugLibTest_raw.tsv'

        base_dir = '.'

    # 1. Load Data
    df_train, df_test = load_data(train_path, test_path)

    # 2. Preprocessing
    X_train_text, y_train, X_test_text, y_test, classes, le = preprocess_data(df_train, df_test)

    # Visualisasi 1 & WordCloud
    plot_class_distribution(y_train, classes, output_file=os.path.join(base_dir, 'distribusi_kelas.png'))
    plot_wordcloud(X_train_text, output_file=os.path.join(base_dir, 'wordcloud.png'))

    # 3. Feature Engineering
    # TF-IDF
    X_train_tfidf, X_test_tfidf, tfidf_vectorizer = get_tfidf_features(X_train_text, X_test_text)
    plot_correlation_heatmap(X_train_tfidf, tfidf_vectorizer.get_feature_names_out(), output_file=os.path.join(base_dir, 'heatmap_korelasi.png'))

    # Sequences (DL)
    X_train_seq, X_test_seq = get_sequence_features(X_train_text, X_test_text)

    # 4. Training
    # Perhatikan: fungsi ini sekarang mengembalikan 3 model juga
    history, scores, base_model, rf_model, dl_model = train_models(
        X_train_tfidf, X_test_tfidf, X_train_seq, X_test_seq,
        y_train, y_test, classes, vocab_size=10000, max_len=200
    )

    # Visualisasi Hasil Model
    plot_model_comparison(scores, output_file=os.path.join(base_dir, 'perbandingan_model.png'))
    plot_training_history(history, output_file=os.path.join(base_dir, 'training_history.png'))

    # 5. Saving Artifacts (Model & Vectorizer)
    save_artifacts(rf_model, dl_model, tfidf_vectorizer, output_dir=base_dir)

    print("\n--- Selesai! Semua grafik dan model telah disimpan. ---")