# -*- coding: utf-8 -*-
"""Ploting Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1biPaUlHZmuIDUtU70jWYH7bo5qkECunJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
import joblib
from wordcloud import WordCloud

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Embedding, GlobalAveragePooling1D, Dropout

#@title Ploting
def plot_class_distribution(y_train, classes, output_file='distribusi_kelas.png'):
    plt.figure(figsize=(10, 6))
    unique, counts = np.unique(y_train, return_counts=True)
    class_labels = [classes[i] for i in unique]
    sns.barplot(x=class_labels, y=counts, palette='viridis')
    plt.title('Visualisasi 1: Distribusi Kelas Target (Effectiveness)')
    plt.xticks(rotation=45)
    plt.tight_layout()
    plt.savefig(output_file)
    print(f"Grafik distribusi disimpan di: {output_file}")

def plot_correlation_heatmap(tfidf_matrix, feature_names, output_file='heatmap_korelasi.png'):
    mean_tfidf = np.array(tfidf_matrix.mean(axis=0)).flatten()
    top_indices = mean_tfidf.argsort()[-30:][::-1]
    top_features_data = tfidf_matrix[:, top_indices].toarray()
    top_feature_names = [feature_names[i] for i in top_indices]
    df_subset = pd.DataFrame(top_features_data, columns=top_feature_names)
    corr_matrix = df_subset.corr()
    plt.figure(figsize=(12, 10))
    sns.heatmap(corr_matrix, cmap='coolwarm', linewidths=0.5, annot=False)
    plt.title('Visualisasi 2: Heatmap Korelasi (30 Fitur Teratas)')
    plt.tight_layout()
    plt.savefig(output_file)
    print(f"Grafik heatmap disimpan di: {output_file}")

def plot_model_comparison(scores, output_file='perbandingan_model.png'):
    plt.figure(figsize=(8, 5))
    models = list(scores.keys())
    accuracies = list(scores.values())
    bars = plt.bar(models, accuracies, color=['gray', 'blue', 'green'])
    plt.ylim(0, 1.0)
    plt.title('Visualisasi 3: Perbandingan Akurasi Model')
    plt.ylabel('Akurasi')
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval + 0.01, round(yval, 3), ha='center', va='bottom')
    plt.tight_layout()
    plt.savefig(output_file)
    print(f"Grafik perbandingan model disimpan di: {output_file}")

def plot_training_history(history, output_file='training_history.png'):
    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Accuracy')
    plt.plot(history.history['val_accuracy'], label='Val Accuracy')
    plt.title('Deep Learning Accuracy')
    plt.legend()
    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Val Loss')
    plt.title('Deep Learning Loss')
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_file)
    print(f"Grafik training history disimpan di: {output_file}")

def plot_wordcloud(text_data, output_file='wordcloud.png'):
    """Visualisasi WordCloud dari seluruh teks ulasan"""
    all_text = " ".join(text_data.astype(str))
    wordcloud = WordCloud(width=800, height=400, background_color='white',
                          max_words=200, colormap='viridis').generate(all_text)
    plt.figure(figsize=(10, 5))
    plt.imshow(wordcloud, interpolation='bilinear')
    plt.axis('off')
    plt.title('Visualisasi: WordCloud Kata yang Sering Muncul')
    plt.tight_layout()
    plt.savefig(output_file)
    print(f"Grafik WordCloud disimpan di: {output_file}")