# -*- coding: utf-8 -*-
"""Save Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1biPaUlHZmuIDUtU70jWYH7bo5qkECunJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import sys
import joblib
from wordcloud import WordCloud

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense, Embedding, GlobalAveragePooling1D, Dropout

def save_artifacts(rf_model, dl_model, vectorizer, output_dir='models'):

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    rf_path = os.path.join(output_dir, 'model_rf.pkl')
    joblib.dump(rf_model, rf_path)
    print(f"\n[SAVED] Random Forest model disimpan di: {rf_path}")

    vec_path = os.path.join(output_dir, 'tfidf_vectorizer.pkl')
    joblib.dump(vectorizer, vec_path)
    print(f"[SAVED] TF-IDF Vectorizer disimpan di: {vec_path}")

    dl_path = os.path.join(output_dir, 'model_dl.keras')
    dl_model.save(dl_path)
    print(f"[SAVED] Deep Learning model disimpan di: {dl_path}")